---
title: "PS_Estimation_CART_Yunuo"
author: "Yunuo Ma"
date: "11/30/2020"
output: pdf_document
---

```{r}
packages.used <- c("grDevices","rpart")
# check packages that need to be installed.
packages.needed <- setdiff(packages.used, 
                           intersect(installed.packages()[,1], 
                                     packages.used))
# install additional packages
if(length(packages.needed) > 0){
  install.packages(packages.needed, dependencies = TRUE)
}
library(grDevices)
library(rpart)
```

```{r}
path = './data/'
highdim = read_csv(paste0(path, 'highDim_dataset.csv')) #2000  187
lowdim = read_csv(paste0(path, 'lowDim_dataset.csv')) #475  24
```

## Regression Trees (CART)
### For High Dimension Data
```{r}
set.seed(0)
prop.fit.high_cart <- highdim[, setdiff(names(highdim), 'Y')]
high_cart <- rpart(A~., data=prop.fit.high_cart, method="class")
best_cp_high <- high_cart$cptable[which.min(high_cart$cptable[,"xerror"]),"CP"]
start.time_ps_high_CART <- Sys.time()
prop.out.high_cart <- rpart(A~., data=prop.fit.high_cart, method="class",cp=best_cp_high, parms = list(split = "information"))
pscore_cart_h <- predict(prop.out.high_cart,type='prob')[,2]
end.time_ps_high_CART <- Sys.time()
high_cp_cart<- highdim
high_cp_cart$pscore=pscore_cart_h
par(xpd = NA) # otherwise on some devices the text is clipped
plot(prop.out.high_cart)
text(prop.out.high_cart, digits = 4)
time_ps_high_CART <- end.time_ps_high_CART - start.time_ps_high_CART
time_ps_high_CART
```

```{r}
col.alpha = function(color,alpha){
  code = col2rgb(color)/256
  rgb(code[1],code[2],code[3],alpha)
}

hist(high_cp_cart$pscore[high_cp_cart$A==1], breaks=20,col=col.alpha('red',.5),freq=FALSE,
     ylim=c(0,35),xlim=c(0.3,0.65),xlab="Propensity Score", ylab="",main="")
lines(density(high_cp_cart$pscore[high_cp_cart$A==1]),col='red')
hist(high_cp_cart$pscore[high_cp_cart$A==0],breaks=20,col=col.alpha('blue',.5),freq=FALSE,
     ylim=c(0,35),xlim=c(0.3,0.65),add=TRUE)
lines(density(high_cp_cart$pscore[high_cp_cart$A==0]),col='blue')
```

### For Low Dimension Data
```{r}
set.seed(0)
prop.fit.low_cart <- lowdim[, setdiff(names(lowdim), 'Y')]
low_cart <- rpart(A~., data=prop.fit.low_cart, method="class")
best_cp_low <- low_cart$cptable[which.min(low_cart$cptable[,"xerror"]),"CP"]
start.time_ps_low_CART <- Sys.time()
prop.out.low_cart <- rpart(A~., data=prop.fit.low_cart, method="class",cp=best_cp_low, parms = list(split = "information"))
pscore_cart_l <- predict(prop.out.low_cart, type='prob')[,2]
end.time_ps_low_CART <- Sys.time()
low_cp_cart<- lowdim
low_cp_cart$pscore=pscore_cart_l
par(xpd = NA) # otherwise on some devices the text is clipped
plot(prop.out.low_cart)
text(prop.out.low_cart, digits = 4)
time_ps_low_CART <- end.time_ps_low_CART - start.time_ps_low_CART
time_ps_low_CART
```

```{r}
hist(low_cp_cart$pscore[low_cp_cart$A==1], breaks=20,col=col.alpha('red',.5),freq=FALSE,
     ylim=c(0,35),xlim=c(0,1),xlab="Propensity Score", ylab="",main="")
lines(density(low_cp_cart$pscore[low_cp_cart$A==1]),col='red')
hist(low_cp_cart$pscore[low_cp_cart$A==0],breaks=20,col=col.alpha('blue',.5),freq=FALSE,
     ylim=c(0,35),xlim=c(0,1),add=TRUE)
lines(density(low_cp_cart$pscore[low_cp_cart$A==0]),col='blue')
```
