---
title: "WeightedRegression"
author: '-'
date: "2020/11/22"
output: html_document
---

```{r}
library(readr)
high <- read_csv("/Users/liloli/Desktop/Project4/highDim_dataset.csv")
low <- read_csv("/Users/liloli/Desktop/Project4/lowDim_dataset.csv")
```

## LowDim Dataset
```{r}
# Assume all covariates have an influence on the assignment to either the control or the treatment group
lr_low <- glm(A~., data=subset(low,select=-Y), family = binomial())
summary(lr_low)
```

```{r}
# Attaching propensity score to the low_dim dataset
low$psvalue <- predict(lr_low, type='response')

# Historgrams for propensity scores
low_treated <- low[low$A==1,]
hist(low_treated$psvalue)

low_controled <-low[low$A==0,]
hist(low_controled$psvalue)
#From two graphs we could see, there is sufficient overlap between the two groups
```


Weights for ATE: We define the weights using:
* for the treatment group: 1/low$psvalue
* for the control group: 1/(1-low$psvalue)
```{r}
# Estimation and storing weights using propensity score estimated using logistic regression
# Attaching weight to the lowdim dataset
low$weight.ATE <- ifelse(low$A == 1, 1/low$psvalue, 1/(1-low$psvalue))
```

Select subset $Z_i$
```{r}
# select variables by weighted regression
weighted_lr_low <- lm(Y~.-psvalue-weight.ATE, data = low, weights = (weight.ATE))
summary(weighted_lr_low)
```
Use 1.96 for $t_{reg}$.
result shows we should not include v2, v4, v9, v14.
Calculate $Z_i$:
```{r}
#low_selected concludes A, Y and all corvariates we want
low_selected <- low %>% select(-V2, -V4,-V9, -V14, -psvalue, -weight.ATE)
```
Calculate the mean od $Z_i$:
```{r}
process_low <- low_selected %>% select(-A, -Y)
mean_Z <- rowMeans(process_low  , na.rm = FALSE, dims = 1)
Ti <- low$A
process_low 
```

```{r}
low_minus_mean <- as_tibble(sapply(process_low, function(x) (x-mean_Z)*Ti))
```

Change column names:
```{r}
low_new_names <- sapply(colnames(low_minus_mean), function(x)     paste(x,"_minus_mean",sep=""))
colnames(low_minus_mean) <- low_new_names
low_minus_mean
```

the data we use for weighted regression to calculate ATE:
```{r}
low_data <- cbind(low_selected,low_minus_mean)
```


Apply the algorithm:
```{r}
# Run weighted regression to find the ATE w/o variable selection
ATE_low_all <- lm(Y~., data = low_data, weights = (low$weight.ATE))
summary(ATE_low_all)
```




