---
title: "Project4 Weighted Regression"
author: "Xiaoli Sun(xs2338)"
date: "11/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Basic Analysis
Load data.
```{r}
library(dplyr)
library(ggplot2)
library(tidyverse)
high = read.csv("/Users/liloli/Desktop/Project4/highDim_dataset.csv")
low = read.csv("/Users/liloli/Desktop/Project4/lowDim_dataset.csv")
```


##High Dimension
```{r}
# Assume all covariates have an influence on the assignment to either the control or the treatment group
lr_high <- glm(A~., data=subset(high,select=-Y), family = binomial())
summary(lr_high)
```
```{r}
# Attaching propensity score to the high_dim dataset
high$psvalue <- predict(lr_high, type='response')

# Historgrams for propensity scores
high_treated <- high[high$A==1,]
hist(high_treated$psvalue)

high_controled <-high[high$A==0,]
hist(high_controled$psvalue)
#From two graphs we could see, there is sufficient overlap between the two groups
```
Weights for ATE: We define the weights using:
* for the treatment group: 1/low$psvalue
* for the control group: 1/(1-low$psvalue)
```{r}
# Estimation and storing weights using propensity score estimated using logistic regression
# Attaching weight to the lowdim dataset
high$weight.ATE <- ifelse(high$A == 1, 1/high$psvalue, 1/(1-high$psvalue))
```
                                                                                    Select subset $Z_i$
```{r}
# select variables by weighted regression
weighted_lr_high <- lm(Y~.-psvalue-weight.ATE, data = high, weights = (weight.ATE))
summary(weighted_lr_high)
```
Use 1.96 for $t_{reg}$.
We should select 
V3, V10, V28, V39, V45, V91, V100, V102, V116, V120, V126, V129, V130, V133, V136, V138, V148, V150, V180.
```{r}
#high_selected concludes A, Y and all corvariates we want
high_selected <- high %>% select(Y,A,V3, V10, V28, V39, V45, V91, V100, V102, V116, V120, V126, V129, V130, V133, V136, V138, V148, V150, V180, -psvalue, -weight.ATE)
```

Calculate the mean od $Z_i$:
```{r}
process_high <- high_selected %>% select(-A,-Y)
mean_Z <- rowMeans(process_high  , na.rm = FALSE, dims = 1)
Ti <- high$A
process_high
```
```{r}
high_minus_mean <- as_tibble(sapply(process_high, function(x) (x-mean_Z)*Ti))
```

Change column names:
```{r}
high_new_names <- sapply(colnames(high_minus_mean), function(x)     paste(x,"_minus_mean",sep=""))
colnames(high_minus_mean) <- high_new_names
high_minus_mean
```
the data we use for weighted regression to calculate ATE:
```{r}
high_data <- cbind(high_selected,high_minus_mean)
```

Apply the algorithm:
```{r}
# Run weighted regression to find the ATE w/o variable selection
ATE_high_all <- lm(Y~., data = high_data, weights = (high$weight.ATE))
summary(ATE_high_all)
```















